#!/usr/bin/env python

import rospy
import roslib

from waveshare_alphabot2.msg import Pan_Tilt

import time
import math
import smbus

# Camera Pan
# Camera Tilt


class PCA9685:
		
	# Registers/etc.
	__SUBADR1		= 0x02
	__SUBADR2		= 0x03
	__SUBADR3		= 0x04
	__MODE1			= 0x00
	__PRESCALE		= 0xFE
	__LED0_ON_L		= 0x06
	__LED0_ON_H		= 0x07
	__LED0_OFF_L	= 0x08
	__LED0_OFF_H	= 0x09
	__ALLLED_ON_L	= 0xFA
	__ALLLED_ON_H	= 0xFB
	__ALLLED_OFF_L	= 0xFC
	__ALLLED_OFF_H	= 0xFD

	def __init__(self, address=0x40, debug=False):
		rospy.loginfo("Node 'camera_pan_tilt' configuring PCA9685")
		self.bus = smbus.SMBus(1)
		self.address = address
		self.debug = debug
		rospy.loginfo("Node 'camera_pan_tilt' Reseting PCA9685")
		self.write(self.__MODE1, 0x00)
		rospy.loginfo("Node 'camera_pan_tilt' PCA9685 configured")
		
	def write(self, reg, value):
		self.bus.write_byte_data(self.address, reg, value)
			
	def read(self, reg):
		# Read an unsigned byte from the I2C device
		result = self.bus.read_byte_data(self.address, reg)
		return result
		
	def setPWMFreq(self, freq):
		# Sets the PWM frequency
		prescaleval = 25000000.0		# 25MHz
		prescaleval /= 4096.0			 # 12-bit
		prescaleval /= float(freq)
		prescaleval -= 1.0
		prescale = math.floor(prescaleval + 0.5)

		oldmode = self.read(self.__MODE1)
		newmode = (oldmode & 0x7F) | 0x10				# sleep
		self.write(self.__MODE1, newmode)				# go to sleep
		self.write(self.__PRESCALE, int(math.floor(prescale)))
		self.write(self.__MODE1, oldmode)
		time.sleep(0.005)
		self.write(self.__MODE1, oldmode | 0x80)

	def setPWM(self, channel, on, off):
		# Sets a single PWM channel
		self.write(self.__LED0_ON_L+4*channel, on & 0xFF)
		self.write(self.__LED0_ON_H+4*channel, on >> 8)
		self.write(self.__LED0_OFF_L+4*channel, off & 0xFF)
		self.write(self.__LED0_OFF_H+4*channel, off >> 8)
			
	def setServoPulse(self, channel, pulse):
		# Sets the Servo Pulse,The PWM frequency must be 50HZ
		pulse = pulse*4096/20000				#PWM frequency is 50HZ,the period is 20000us
		self.setPWM(channel, 0, pulse)

	def __del__(self):
		self.write(self.__MODE1, 0x00)


class camera_pan_tilt_driver:
	#  Set HPulse and VPulse to half way (500 to 2500)
	HPulse = 1500
	VPulse = 1500

	def __init__(self):
		rospy.init_node("camera_pan_tilt_driver")
		rospy.loginfo("Node 'camera_pan_tilt' configuring driver")

		self.rate = rospy.Rate(rospy.get_param('~rate', 10))

		self.pwm = PCA9685(0x40)
		self.pwm.setPWMFreq(50)

		#Set the Horizontal servo parameters
		self.pwm.setServoPulse(0,self.HPulse)

		#Set the vertical servo parameters
		self.pwm.setServoPulse(1,self.VPulse)

		# Setup subscriber for pan_tilt message
		rospy.Subscriber('pan_tilt', Pan_Tilt, self.pan_tilt_callback)
		rospy.loginfo("Node 'camera_pan_tilt' configured")

	def run(self):
		rospy.loginfo("Node 'pan_tilt' running.")
		while not rospy.is_shutdown():
			self.rate.sleep()

	def pan_tilt_callback(self, message):
		rospy.loginfo("Node 'camera_pan_tilt' message received.")
		
		pan = message.pan
		tilt = message.tilt
		rospy.loginfo("Node 'camera_pan_tilt' Pan= "+str(pan)+".")
		rospy.loginfo("Node 'camera_pan_tilt' Tilt="+str(tilt)+".")

		# Convert from radians to pulses (500 - 2500)
		self.HPulse = int(-pan  * (1000 / (math.pi / 2)) + 1500)
		self.VPulse = int(-tilt * (1000 / (math.pi / 2)) + 1500)
		
		self.pwm.setServoPulse(1,self.VPulse)
		self.pwm.setServoPulse(0,self.HPulse)

def main():
	rospy.loginfo("Starting node 'camera_pan_tilt'")
	driver = camera_pan_tilt_driver()
	driver.run()
	rospy.loginfo("Node 'camera_pan_tilt' Stopped")

if __name__ == '__main__':
	main()
